version: '3.1'

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: somepassword
    ports:
      - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080